# Generated by Django 5.1.4 on 2025-11-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
        ("rankings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryGlobalRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do País"
                    ),
                ),
                (
                    "user_count",
                    models.IntegerField(
                        default=0, verbose_name="Número de Usuários Ativos"
                    ),
                ),
                (
                    "analysis_data",
                    models.JSONField(
                        default=dict, verbose_name="Dados Completos da Análise (JSON)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consensus_album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="country_consensus",
                        to="albums.album",
                        verbose_name="Álbum Favorito (Consenso)",
                    ),
                ),
                (
                    "polarization_album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="country_polarization",
                        to="albums.album",
                        verbose_name="Álbum da Maior Polarização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking Global por País",
                "verbose_name_plural": "Rankings Globais por País",
            },
        ),
    ]
