# Generated by Django 5.2.8 on 2025-11-20 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('rankings', '0003_countryglobalranking_global_consensus_track'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranking do Usuário',
                'verbose_name_plural': 'Rankings dos Usuários',
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='RankedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Posição da track no ranking do usuário (1 sendo o favorito).')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
                ('user_ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_tracks', to='rankings.userranking')),
            ],
            options={
                'verbose_name': 'Track Rankeada',
                'verbose_name_plural': 'Tracks Rankeadas',
                'ordering': ['position'],
                'unique_together': {('user_ranking', 'track', 'position')},
            },
        ),
    ]
