# Generated by Django 5.2.8 on 2025-11-20 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
        ("rankings", "0004_userranking_rankedtrack"),
        ("social", "0002_groupinvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rankedtrack",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="userranking",
            options={"verbose_name": "Submissão de Ranking Individual"},
        ),
        migrations.AlterUniqueTogether(
            name="rankedtrack",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userranking",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rankedtrack",
            name="position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="userranking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GroupRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.album"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings_to_complete",
                        to="social.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking de Grupo",
                "unique_together": {("group", "album")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="userranking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userranking",
            name="group_ranking",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="rankings.groupranking",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="userranking",
            unique_together={("group_ranking", "user")},
        ),
        migrations.RemoveField(
            model_name="userranking",
            name="album",
        ),
        migrations.RemoveField(
            model_name="userranking",
            name="updated_at",
        ),
    ]
